services:
  frontend:
    image: empreinte-souffrance.remigirard.dev:5000/admin/empreinte-souffrance_frontend:${STAGE_NAME}
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.`${TRAEFIK_ROUTER_NAME}`.rule=Host(`${DEPLOY_URL}`)"
        - "traefik.http.routers.`${TRAEFIK_ROUTER_NAME}`.entrypoints=websecure"
        - "traefik.http.routers.`${TRAEFIK_ROUTER_NAME}`.tls.certresolver=wildcardresolver"
        - "traefik.http.services.`${TRAEFIK_ROUTER_NAME}`.loadbalancer.server.port=3000"
networks:
  traefik-public:
    external: true
